version: "3.3"
services:
  ceditor:
    image: 'ceditordev:${TAG-latest}'
    container_name: ceditor-solo
    env_file:
      - .env.solo
    environment:
      - PROTOCOL=http://
      - SERVER_NAME=${DOMAIN?Variable not set}:${WRAPPER_SOLODEVPORT}
      - PORT=${WRAPPER_PORT}
      - BASE_PATH=
      - MONGODB_URL=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}?retryWrites=true&w=majority
    volumes:
      - ./ceditor:/app
    build:
      context: ./ceditor
      dockerfile: Dockerfile
      target: dev
    ports:
      - "${WRAPPER_SOLODEVPORT}:${WRAPPER_PORT}"
    networks:
      - default
      
  etherpad:
    container_name: etherpad-solo
    build:
      context: ./etherpad
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "${ETHERPAD_SOLODEVPORT}:${ETHERPAD_PORT}"
    environment:
      - TITLE=${ETHERPAD_TITLE}
      - PORT=${ETHERPAD_PORT}
      - DEFAULT_PAD_TEXT=${ETHERPAD_DEFAULT_PAD_TEXT}
      - ETHERPAD_API_KEY=${ETHERPAD_API_KEY}
      - ADMIN_PASSWORD=${ETHERPAD_ADMIN_PASSWORD}
      - ADMIN_USER=${ETHERPAD_ADMIN_USER}
      - REQUIRE_SESSION=${ETHERPAD_REQUIRE_SESSION}
      - EDIT_ONLY=${ETHERPAD_EDIT_ONLY}
      - MONGODB_URL=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}?retryWrites=true&w=majority
    networks:
      - default

  mongodb:
    image: bitnami/mongodb:latest
    container_name: etherpad-mongodb
    env_file:
      - .env.solo
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $MONGODB_ROOT_USER -p $MONGODB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - default